[build]
  # Build command for Vite
  command = "npm run build"
  
  # Output directory for the built site
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (you'll set these in Netlify dashboard)
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"